# Generated by Django 5.1.2 on 2024-10-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dangerarea_dangerpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='dangerarea',
            name='type',
            field=models.CharField(default='danger', max_length=100),
        ),
    ]
